### ISSUE TITLE
Listar os projetos mais ativos e/ou populares de cada membro

### ISSUE THREAD

**Issue by skhaz** [ccppbrasil/ccppbrasil.github.io#7]
Usando a API do próprio Github, ou do GoogleCode, Bitbucket, SourceForge, etc. Listar os 5 projetos escritos em C ou C++ mais ativos e/ou populares de cada membro público da organização.
O que acham?

**Comment by CoolerVoid** [comment]
fazendo um crawler desse cara http://github-awards.com/users/search?login=oblitum depois um sort das hash tables resolve...

cheers.
